### ISSUE TITLE
Incorrect variable name in code lab step 8

### ISSUE THREAD

**Issue by zaidkazi** [googlecodelabs/admob-inline-ads-in-flutter#1]
` NativeAd _nativeAd;` is defined although the variable should be  `NativeAd _ad`

It seems only the code lab has the typo the actual project seems fine.
 
 https://codelabs.developers.google.com/codelabs/admob-inline-ads-in-flutter#7

**Comment by kunny** [comment]
Updated the content - Thanks!

**Comment by zaidkazi** [comment]
Np! Cheers
