### ISSUE TITLE
Native Ads issue on android

### ISSUE THREAD

**Issue by ausk47** [googlecodelabs/admob-inline-ads-in-flutter#11]
This ad may have not been loaded or has been disposed. Ad with the following id could not be found: 3.

**Comment by kunny** [comment]
Error code 3 can be caused by many reasons and it could happen sometimes. I strongly encourage you to check out the [Can't see ads Troubleshooter](https://support.google.com/admob/troubleshooter/9092685?hl=en&ref_topic=2961358) for your case.
