### ISSUE TITLE
Havent Changes Codelab code for implementing Native Ads in Flutter with new class name

### ISSUE THREAD

**Issue by TusharPatel18** [googlecodelabs/admob-inline-ads-in-flutter#12]
Most classes related to UnifiedNativeAd have been renamed to NativeAd in com.google.android.gms:play-services-ads:19.7.0,
please make a changes in codelab code and give proper example ,also give proper example with changes in google_mobile_ads: ^0.12.1+1 flutter package. Thank you ;)
codelab: https://codelabs.developers.google.com/codelabs/admob-inline-ads-in-flutter#7

**Comment by kunny** [comment]
I need to wait until the `google_mobile_ads_flutter` supports it. 

FYI - currently the plugin team is working on updating the plugin to support the latest Google Mobile Ads SDK:  (https://github.com/googleads/googleads-mobile-flutter/pull/214).

**Comment by tp-coderbabu** [comment]
> I need to wait until the `google_mobile_ads_flutter` supports it.
> 
> FYI - currently the plugin team is working on updating the plugin to support the latest Google Mobile Ads SDK: ([googleads/googleads-mobile-flutter#214](https://github.com/googleads/googleads-mobile-flutter/pull/214)).

please change it now
Thank you.

**Comment by kunny** [comment]
Please track the progress from #16.
