### ISSUE TITLE
Codelab: Step 5, use provided test IDs

### ISSUE THREAD

**Issue by jagomf** [googlecodelabs/admob-inline-ads-in-flutter#13]
In step 5, you provide a snippet in case you want to use test IDs:
```dart
import 'dart:io';

class AdHelper { // renamed in code to AdManager
  
  static String get bannerAdUnitId {
    if (Platform.isAndroid) {
      return 'ca-app-pub-3940256099942544/6300978111';
    } else if (Platform.isIOS) {
      return 'ca-app-pub-3940256099942544/2934735716';
    }
    throw new UnsupportedError("Unsupported platform");
  }

  static String get nativeAdUnitId {
    if (Platform.isAndroid) {
      return 'ca-app-pub-3940256099942544/2247696110';
    } else if (Platform.isIOS) {
      return 'ca-app-pub-3940256099942544/3986624511';
    }
    throw new UnsupportedError("Unsupported platform");
  }
}
```

You should instead use the IDs **provided by the plugin** itself:
```dart
import 'package:google_mobile_ads/google_mobile_ads.dart';

class AdHelper { // renamed in code to AdManager

  static String get bannerAdUnitId => BannerAd.testAdUnitId;

  static String get nativeAdUnitId => NativeAd.testAdUnitId;
}
```

**Comment by kunny** [comment]
Thanks for your feedback! However, it is intended as the plugin team is planning to remove that property from the plugin in the future release.

Note that test ad unit IDs in the codelab are the official AdMob test ad unit IDs. ([Android](https://developers.google.com/admob/android/test-ads), [iOS](https://developers.google.com/ios/android/test-ads))

**Comment by jagomf** [comment]
> the plugin team is planning to remove that property from the plugin in the future release

Wow, are they? I don't see the point of that... Keeping the official AdMob test ad unit IDs as a constant is really useful.
