### ISSUE TITLE
Does not work with google_mobile_ads 0.13.0

### ISSUE THREAD

**Issue by codespair** [googlecodelabs/admob-inline-ads-in-flutter#16]
First things first:  nice tutorial thanks! Gr8 work. 

I noticed the lab does not work with latest version available due to the entry  ( I know the correct version is mentioned in the start 0.12)

listener: AdListener(
        onAdLoaded: (_) {
          setState(() {
            _isAdLoaded = true;
          });
        },

AdListener is not there in 0.13.0 which is fine but then I would expect to find at least a mention in the 0.13.0 documentation here: 

https://pub.dev/packages/google_mobile_ads/changelog

but I didn't find any mention to it. 
I will try to make it work anyway with 0.13.0 and post the solution here if I manage to find it. 

Best,
Codespair

**Comment by kunny** [comment]
Thanks for the report! I'm working on updating the documentation as well as the sample code. Will let you know once it's done.

**Comment by kunny** [comment]
Done updating [the doc](https://codelabs.developers.google.com/codelabs/admob-inline-ads-in-flutter#3) and sample code :)
