### ISSUE TITLE
AdMobs no longer using UnifiedNativeAdView but NativeAdView instead

### ISSUE THREAD

**Issue by mouseface99** [googlecodelabs/admob-inline-ads-in-flutter#18]
newer version of `play-services-ads` also cannot find `com.google.android.gms.ads.formats.UnifiedNativeAd` or marked as @deprecated

but this code lab document still using these classes (`Unifiedxxx`)

**Comment by kunny** [comment]
Thanks for the report! Please track the progress from #16.
