### ISSUE TITLE
Confusing statement in the page 5 of the codelab

### ISSUE THREAD

**Issue by rocboronat** [googlecodelabs/admob-inline-ads-in-flutter#21]
[In the fifth page of the codelab](https://codelabs.developers.google.com/codelabs/admob-inline-ads-in-flutter#4) you say that we should put the app ID in a file, but then you don't do it. I think it's a deprecated statement because we added the app ID in the AndroidManifest / Info.plist files, so I think we won't need it again.

**Comment by kunny** [comment]
Translation might be out-of-date I think. Could you check out the base version (in English) instead?

**Comment by rocboronat** [comment]
Well, I was just reporting the issue 😝
