### ISSUE TITLE
Why is `GADNativeAd.h` needed?

### ISSUE THREAD

**Issue by gaborszakacs** [googlecodelabs/admob-inline-ads-in-flutter#23]
This file was added to the example repo when making the code 0.13.x compatible, but this is already part of the iOS SDK itself if I understand it correctly. Why do we need it, does it need to be modified? If so, should we document the changes needed?

https://github.com/googlecodelabs/admob-inline-ads-in-flutter/commit/68d8fe768fb8a2915d301be1ebf102029f94c6fb#diff-1108c7aa36e51c7e38cb70447c3c1269a3624e880bc8ecff6614b2b6135e7656

**Comment by kunny** [comment]
I added `GADNativeAd.h` file to enable [outlets](https://developers.google.com/admob/ios/native/advanced) enabled in Xcode. While `GADNativeAd.h` is already included as a dependency, Xcode does not populate outlets in the inspector pane, which blocks you from linking outlets to `UIView`s for your native ad layout.

However, without the header file included in the project, you should be able to build & run the project anyway. So it's up to you whether leaving the header file in the project folder, or remove it after you done with linking outlets to the ad view.
