### ISSUE TITLE
Ad load failed (code=3 message=No ad config.)

### ISSUE THREAD

**Issue by sultanmyrza** [googlecodelabs/admob-inline-ads-in-flutter#25]
anybody getting issue
```
I/Ads     (28721): Ad failed to load : 3
I/flutter (28721): Ad load failed (code=3 message=No ad config.)
```

**Comment by kunny** [comment]
Error code 3 (on Android) means there's no ad to show, so it's likely to be an intended behavior. If you'd like to test ad serving for development, I would encourage you to use [demo ad units](https://developers.google.com/admob/android/test-ads#demo_ad_units) since it always return ads.
