### ISSUE TITLE
Error in code

### ISSUE THREAD

**Issue by Cubel89** [googlecodelabs/admob-inline-ads-in-flutter#26]
There is an error in the code in point 4
[https://codelabs.developers.google.com/codelabs/admob-inline-ads-in-flutter#6](url)
      
"listener: AdListener(" has to be replaced by "listener: BannerAdListener(" in initState()

**Comment by kunny** [comment]
Fixed in the latest update. ([6358603](https://github.com/googlecodelabs/admob-inline-ads-in-flutter/commit/63586032c0438c822089e453c1aacd3b577ccdeb)). Thanks!
