### ISSUE TITLE
Does this follow AdMob Policy

### ISSUE THREAD

**Issue by MattyBoy4444** [googlecodelabs/admob-inline-ads-in-flutter#27]
I just want to make sure I do not get banned from AdMob.  Using a BannerAd inline in a list may violate your policies and get me Banned. 

[https://support.google.com/admob/answer/6275345](https://support.google.com/admob/answer/6275345)
The video at the bottom states to NOT have banner ads that scroll in a menu.  So, does this violate the policy?

I sure wish there was a better way to find out violations with specifics BEFORE you get banned and have time to fix!!

Second question, If I load two different Banners for the List am I violating your policies?   

This seems like basic information that should be shared to help developers know what you want us to do.  Please HELP!!

**Comment by kunny** [comment]
Unfortunately I can't cover policy topics here. Please reach out to AdMob help center to get your questions answered properly :)
