### ISSUE TITLE
Spelling miss

### ISSUE THREAD

**Issue by takaaltitude** [googlecodelabs/admob-inline-ads-in-flutter#29]
NOT UnitifedNativeAdView but UnifiedNativeAdView
[https://codelabs.developers.google.com/codelabs/admob-inline-ads-in-flutter?hl=ja#7](url)
in the No.4
<img width="823" alt="Screen Shot 0003-10-27 at 14 18 49" src="https://user-images.githubusercontent.com/60106224/139004481-9b50dab8-6c70-4553-beed-4c14323a637f.png">

**Comment by kunny** [comment]
The fix has been pushed out. Thanks for your report!
