### ISSUE TITLE
wrong file name in the admob-ads-in-flutter codelab

### ISSUE THREAD

**Issue by asavchuk** [googlecodelabs/admob-inline-ads-in-flutter#34]
in [Adding AdMob ads to a Flutter app, step 7](https://codelabs.developers.google.com/codelabs/admob-ads-in-flutter#6)
here in sentence
`Open the lib/game_route.dart file, and import ad_manager.dart`
there is no _ad_manager.dart_ in the source, so there should be
`Open the lib/game_route.dart file, and import ad_helper.dart`

moreover, it is beter to write
`Open the lib/game_route.dart file` under the first step, because all the required imports has already been pointed in the second step.

**Comment by kunny** [comment]
Fixed in the latest update. Thanks for your report!
