### ISSUE TITLE
Build failed due to use of deprecated Android v1 embedding

### ISSUE THREAD

**Issue by ldobreira** [googlecodelabs/admob-inline-ads-in-flutter#36]
Unfortunately, the example app is not really running out of the box...

**Comment by ldobreira** [comment]
I created a pull request to fix the issue.

**Comment by kunny** [comment]
Thanks for your report! I included the fix with the recent major code update. (https://github.com/googlecodelabs/admob-inline-ads-in-flutter/commit/63586032c0438c822089e453c1aacd3b577ccdeb)
