### ISSUE TITLE
RaisedButton is deprecated

### ISSUE THREAD

**Issue by Tezza27** [googlecodelabs/admob-inline-ads-in-flutter#5]
'RaisedButton' is deprecated and shouldn't be used. Use ElevatedButton instead. See the migration guide in flutter.dev/go/material-button-migration-guide). This feature was deprecated after v1.25.0-8.1.pre..
Try replacing the use of the deprecated member with the replacement.

**Comment by fathah** [comment]
Alternative buttons such as ```TextButton```, ```ElevatedButton```, and ```OutlinedButton``` are not quite easy like before. We can still use those legacy buttons using the [legacy_buttons](https://pub.dev/packages/legacy_buttons/) package

https://pub.dev/packages/legacy_buttons/

**Comment by Blaq5** [comment]
why cant we use raised button no more p.s i am new to flutterr

**Comment by fathah** [comment]
@Blaq5 
`RaisedButton` is deprecated and we can't use that in the latest releases. There might be some problems with RaisedButton, so the Flutter team has introduced `ElevatedButton` as a replace to `RaisedButton` .
So we can use `ElevatedButton` instead. If you're still messed up in using new implementation, you can use the  [legacy_buttons](https://pub.dev/packages/legacy_buttons/) package
which implements those buttons without deprecation warnings. 
🙂
