### ISSUE TITLE
Native ad load failed

### ISSUE THREAD

**Issue by nhacvanbien** [googlecodelabs/admob-inline-ads-in-flutter#7]
Ad load failed (code=0 message=Internal error.)

I/Ads     ( 6781): Received log message: <Google:HTML> Incorrect native ad response. Click actions were not properly specified

**Comment by kunny** [comment]
I have seen this issue on my end as well. I believe it should be a temporary issue of the test ad unit itself.
Could you try to load ads with your own ad unit ID?

**Comment by nhacvanbien** [comment]
Thanks. It works with my own ad unit ID.
