### ISSUE TITLE
Prepare for iOS 14+ 

### ISSUE THREAD

**Issue by sultanmyrza** [googlecodelabs/admob-inline-ads-in-flutter#8]
I have no iOS experience.

to prepare [admob-inline-ads-in-flutter/complete_kotlin_swift/](https://github.com/googlecodelabs/admob-inline-ads-in-flutter/tree/main/complete_kotlin_swift) for [iOS 14+](https://developers.google.com/admob/ios/ios14)

Do we need extra settings?

**Comment by kunny** [comment]
For the `SKAdNetwork`, you can follow the [developer documentation](https://developers.google.com/admob/ios/ios14#skadnetwork) as you have access to the `Info.plist` file.

Additionally, if you want to display the [App Tracking Transparency authorization request](https://developers.google.com/admob/ios/ios14#request), you may want to use the [app_tracking_transparency](https://pub.dev/packages/app_tracking_transparency) plugin.
